### ISSUE TITLE
之前购买过LayIM 没有下载下来，现在怎么办？？？

### ISSUE THREAD

**Issue by DolphinHome** [sentsin/layui#1003]

**Comment by sentsin** [comment]
您好，关于 layui 文档和 layuiAdmin 的迁移，详见：https://gitee.com/layui

**Comment by DolphinHome** [comment]
好的，谢谢

**Comment by DolphinHome** [comment]
关于 layui 文档和 layuiAdmin 的迁移，详见：https://gitee.com/layui，
这个会永久维护吗？还是临时维护，过渡期使用？
