### ISSUE TITLE
table.render中where传参是from-data方式，传中文是乱码。请问可以用raw方式传参数吗？

### ISSUE THREAD

**Issue by ZhuDiyao** [sentsin/layui#1017]
table.render中where传参是from-data方式，传中文是乱码。请问可以用raw方式传参数吗？

**Comment by ZhuDiyao** [comment]
不好意思各位。
通过设置 method 和 contentType ，即可解决问题。

layui.use('table', function(){
              var table = layui.table;
              //第一个实例
              table.render({
                elem: '#demo'
                ,method:'post'
                ,contentType: 'application/json'
                ,height: 'full-300'
                ,limit:50
                ,limits:[10,20,30,40,50,60,70,80,90,100,150,200]
                ,url: '' //数据接口
                ,text:{
                    none:'数据开小差了'
                }
                ,where: {
                    where_SHP: document.getElementById("SHP").value,
                    where_gys: document.getElementById("gys").value,
                    where_dizhi: document.getElementById("dizhi").value
                }

**Comment by ZhuDiyao** [comment]
打扰了 各位

**Comment by Anryliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
