### ISSUE TITLE
强烈建议文件上传接口添加上传进度回调方法

### ISSUE THREAD

**Issue by yuxiao97** [sentsin/layui#153]
文件上传进度在上传中是关注度非常高的一个功能,且最为普遍,希望作者可能添加该功能,最好同时添加上传速率的获取,现在的问题是,自己实现了服务的获取速率,前端通过轮询来获取进度,但这样子的实现方式存在两个问题,
1:每次轮询都属于不同的请求,而服务端则是将进度的更新放到上传请求的session中的,这样导致了轮询和上传
请求不是同一个,无法正常获取进度的问题
2:多人同时上传时会出现进度条篡乱的现象
不知谁有更好的实现方案

**Comment by Yuxiao97** [comment]
参考前人的思想，在2.2.5的版本中，个人修改了upload.js，添加上传进度监听及回调，有需要的可移步https://github.com/Yuxiao97/SpringBootFileUploadWithProgress 进行参考，上传页面为uploadPage.html
