### ISSUE TITLE
这个插件居然没有 npm 安装

### ISSUE THREAD

**Issue by zboboan** [sentsin/layui#185]
请问一下，什么时候出一个  npm 安装的

**Comment by sentsin** [comment]
https://www.npmjs.com/package/layui-src

**Comment by zboboan** [comment]
还是要 script  在 index.html 里引入嘛？不能用 import 这样引入相应的模块？

**Comment by zboboan** [comment]
如果还是要在index.html 里用 script 用局引入，那用不用npm 安装，都还不是一样
