### ISSUE TITLE
选项卡 嵌套 数据表格 时高度计算错误

### ISSUE THREAD

**Issue by Null-C** [sentsin/layui#267]
下面是重现 bug 的 demo：
``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <title>数据表格 BUG 测试</title>
</head>
<link rel="stylesheet" type="text/css" href="./res/layui/css/layui.css">
<script type="text/javascript" src="./res/layui/layui.js"></script>

<body>

    <div class="layui-tab layui-tab-brief">
        <ul class="layui-tab-title">
            <li class="layui-this">日志列表</li>
            <li>草稿列表</li>
        </ul>
        <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <table id="table1"></table>
            </div>
            <div class="layui-tab-item">
                <table id="table2"></table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        layui.use(['element', 'table'], function(){
            var table = layui.table;

            function render(id){
                table.render({
                    elem: id,
                    page: true,
                    limit: 10,
                    limits: [10, 50, 100],
                    loading: true,
                    height: 315,
                    cols: [[
                        {field: 'check', title: '全选', width: 50, type: 'checkbox', fixed: 'left'},
                        {field: 'id', title: 'ID', width: 70},
                        {field: 'title', title: '标题', width: 300},
                        {field: 'sorts', title: '分类', width: 120}
                    ]],
                    data: [
                        {'id': 1, 'title': '这是一篇日志', 'sorts': '日志'},
                        {'id': 2, 'title': '这是第二篇日志', 'sorts': '日志'}
                    ]
                });
            }
            
            render('#table1');
            render('#table2');
        });
    </script>

</body>
</html>
```

**正常显示：**
![1](https://user-images.githubusercontent.com/27117753/41217139-88f97da6-6d89-11e8-9569-f75263d4e157.jpg)

**非正常显示：**
![2](https://user-images.githubusercontent.com/27117753/41217158-94f5463a-6d89-11e8-8120-2a5da83fb2fb.jpg)
应该是数据表格高度计算错误，导致分页条被顶下去了。

测试环境：win7 / chrome 55 / layui-v2.3.0

**Comment by Null-C** [comment]
怀疑计算数据表格高度的时候受`layui-show`样式影响。
我自己临时方案是每个选项卡都添加`layui-show`样式，然后在页面加载后渲染完表格时去除`layui-show`。这样至少能正常显示分页条。

``` html
<div class="layui-tab layui-tab-brief">
    <ul class="layui-tab-title">
        <li class="layui-this">日志列表</li>
        <li>草稿列表</li>
    </ul>
    <div class="layui-tab-content">
        <div class="layui-tab-item layui-show">
            <table id="table1"></table>
        </div>
        <div class="layui-tab-item layui-show">
            <table id="table2"></table>
        </div>
    </div>
</div>
```

``` javascript
var bug = document.querySelector('.layui-tab-item:nth-child(2)');
bug.classList.remove("layui-show");
```

**Comment by cyntdmc** [comment]
element.tabChange(filter, layid); 
| 用于外部切换到指定的Tab项上，参数同上，如： element.tabChange('demo', 'layid'); //切换到 lay-id="yyy" 的这一项
-- | --

 <div class="layui-tab" style="background:white !important; "  lay-filter="demoTab">
            <ul class="layui-tab-title">
                <li class="layui-this" lay-id="tabthis">可派单维护列表</li>
                <li class="layui-this">低电量列表</li>
                <li class="layui-this">低电压列表</li>
            </ul>
            <div class="layui-tab-content" >
                <div class="layui-tab-item   layui-show " >
                    <table class="layui-hide" id="addOperationMaintain" lay-filter="demo"></table>
                </div>
                <div class="layui-tab-item  layui-show ">
                    <table class="layui-hide" id="lowElectricQuantity" lay-filter="demo"></table>
                </div>
                <div class="layui-tab-item   layui-show ">
                    <table class="layui-hide" id="lowVoltage" lay-filter="demo"></table>
                </div>
            </div>
        </div>



        layui.use('element', function () {
            var $ = layui.jquery
                , element = layui.element; //Tab的切换功能，切换事件监听等，需要依赖element模块

            $('.site-demo-active').on('click', function () {
                var othis = $(this), type = othis.data('type');
                active[type] ? active[type].call(this, othis) : '';
            });

            setTimeout(function () {
                element.tabChange('demoTab', 'tabthis');
            }, 1000);
           
        });

**Comment by cyntdmc** [comment]
element.tabChange(filter, layid);
用于外部切换到指定的Tab项上，参数同上，如： 
element.tabChange('demo', 'layid'); //切换到 lay-id="yyy" 的这一项
`
<div class="layui-tab" style="background:white !important; "  lay-filter="demoTab">
            <ul class="layui-tab-title">
                <li class="layui-this" lay-id="tabthis">可派单维护列表</li>
                <li class="layui-this">低电量列表</li>
                <li class="layui-this">低电压列表</li>
            </ul>
            <div class="layui-tab-content" >
                <div class="layui-tab-item   layui-show " >
                    <table class="layui-hide" id="addOperationMaintain" lay-filter="demo"></table>
                </div>
                <div class="layui-tab-item  layui-show ">
                    <table class="layui-hide" id="lowElectricQuantity" lay-filter="demo"></table>
                </div>
                <div class="layui-tab-item   layui-show ">
                    <table class="layui-hide" id="lowVoltage" lay-filter="demo"></table>
                </div>
            </div>
        </div>
`

`

        layui.use('element', function () {
            var $ = layui.jquery
                , element = layui.element; //Tab的切换功能，切换事件监听等，需要依赖element模块

            $('.site-demo-active').on('click', function () {
                var othis = $(this), type = othis.data('type');
                active[type] ? active[type].call(this, othis) : '';
            });

            setTimeout(function () {
                element.tabChange('demoTab', 'tabthis');
            }, 1000);
`

**Comment by Null-C** [comment]
新版本已经修复这个bug了。
