### ISSUE TITLE
关于代码规范

### ISSUE THREAD

**Issue by gaosuccess** [sentsin/layui#278]
首先感谢贤心这一伟大的作品。

最近在研习 layui 的源码，关于代码规范，提出一点建议，希望可以添加 .editorconfig 提供编辑器统一配置。

谢谢你的时间来查看 issue.

**Comment by gaosuccess** [comment]
看到已有相关 PR #263

**Comment by xuexb** [comment]
👍

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
