### ISSUE TITLE
关于表格全选

### ISSUE THREAD

**Issue by nabaonan** [sentsin/layui#30]
我用datatable生成表格，前面的checkbox是动态生成的，点击全选将其他checkbox状态设置和全选按钮一致，并调用form.render（），前两次都能管用，但是第三次就失效了，希望能更改一下这个bug，如果不调用form的render，更改checkbox后如何主动触发按钮变更状态

**Comment by sentsin** [comment]
每次触发全选时，都需要执行一遍：form.render('checkbox');
layui 2.0会有全新的数据表格，建议到时候用layui自身的

**Comment by nabaonan** [comment]
layui2大概什么时候发布，这个问题我已解决，但是很怪异，我用prop设置就好用，用attr设置就不好用，不是由render导致的，不太理解为什么会导致这个问题，网上查了一下，jquery推荐设置比如checked这样自带属性用prop，自定义属性用attr
