### ISSUE TITLE
layui.use 加载顺序问题

### ISSUE THREAD

**Issue by zhongjq** [sentsin/layui#335]
![image](https://user-images.githubusercontent.com/1228323/45334986-e45cee80-b5af-11e8-9080-84464ac701d0.png)
![image](https://user-images.githubusercontent.com/1228323/45334998-ee7eed00-b5af-11e8-8615-d4d7edf14431.png)
![image](https://user-images.githubusercontent.com/1228323/45335022-02c2ea00-b5b0-11e8-9d0b-9e58756fbfe5.png)

如图，写在后面的代码居然先执行了。为什么会这样

**Comment by zhongjq** [comment]
@sentsin 这个bug能修复吗

**Comment by sentsin** [comment]
这个不是什么 BUG，layui.use 是异步执行的

**Comment by zhongjq** [comment]
问题是，异步执行也应该按照我代码编写的顺序执行啊，后写的代码先执行，这样很多组件的全局配置都乱套了，全局配置把调用时传入的配置给覆盖了

**Comment by sentsin** [comment]
@zhongjq 好好去文档里面详细了解下 layui 的模块加载机制

**Comment by sentsin** [comment]
你这种情况，可以建一个共同模块用来进行一些全局配置，如：config.js，在该模块里面写 table.set。
然后在任何用到 table 的地方，layui.use(['config']) 即可。所以你还是没搞明白 layui 的模块依赖关系。

**Comment by zhongjq** [comment]
> 你这种情况，可以建一个共同模块用来进行一些全局配置，如：config.js，在该模块里面写 table.set。
> 然后在任何用到 table 的地方，layui.use(['config']) 即可。所以你还是没搞明白 layui 的模块依赖关系。

明白，这是一种解决方法，但我上面提的问题感觉跟模块依赖没关，就是先写了config.js 里面调用了table.set(....);
<script src="config.js"></script>
<script>
layui.use(['table'], ...);
</script>
就是执行顺序问题，config.js和内联的js之间我没有设置他们有依赖关系的,他们只是都依赖table模块
