### ISSUE TITLE
layUI/JQuery table 内存泄漏问题

### ISSUE THREAD

**Issue by 12Tall** [sentsin/layui#386]
layUI 的table 模块在重新加载数据时（其他元素也存在，table 更明显），用Chrome 的Devtool 查看内存会发现nodes 一直增加，大致能猜测是JQuery 关于DOM 节点操作的某些特性导致（例如不能彻底删除DOM 节点），请问应该怎么解决，谢谢！

**Comment by 12Tall** [comment]
此问题已解决，参考代码：


```javascript
$.fn.removeWithoutLeaking = function() {
    this.each(function(i,e){
        if( e.parentNode )
            e.parentNode.removeChild(e);
    });
};
```


地址：https://stackoverflow.com/questions/1462649/jquery-memory-leak-with-dom-removal

**Comment by woeoio** [comment]
请问具体是table模块哪个地方改动？

**Comment by 12Tall** [comment]
@woeoio 抱歉，因为很久没有用到layui 了，具体问题已经找不到了。这里是在`JQuery`  中新增了一个函数`removeWithoutLeaking()`。用于彻底移除DOM 节点。

**Comment by woeoio** [comment]
是的，我也搜索到是 jq 的内存泄漏问题，然后看到这里，所以问问是哪个地方调用这个函数去彻底清除，，，如果不记得的话我再找找好了。谢谢

**Comment by cty901** [comment]
现在有办法解决了没有？？我被这个问题弄的郁闷几天了~~

**Comment by 12Tall** [comment]
> 现在有办法解决了没有？？我被这个问题弄的郁闷几天了~~

看上面👆
