### ISSUE TITLE
默认msg3秒后自动消失 怎么全局更改成两秒 

### ISSUE THREAD

**Issue by galikeoy** [sentsin/layui#431]
如题 表单验证，或者其他什么提示，停留的时间个人觉得太长了，但是又找不到地方改，可以全局初始化config吗
```javascript
layui.use(['element','layer'], function(){
var layer = layui.layer;
	  layer.config({
	  	time: 2000
	  })
})
```
貌似无效，求解

**Comment by qq1126879104** [comment]
进行二次封装即可

**Comment by galikeoy** [comment]
> 进行二次封装即可

不太懂，可以说详细一点吗，

**Comment by qinzhixian** [comment]
` function myMsg(msg,callback) {
        layer.msg(msg, {time:2*1000},callback)
    };
    myMsg('msg');`

**Comment by galikeoy** [comment]
> ` function myMsg(msg,callback) { layer.msg(msg, {time:2*1000},callback) }; myMsg('msg');`

非常感谢，是我太笨了，看到代码豁然开朗

**Comment by galikeoy** [comment]
> > ` function myMsg(msg,callback) { layer.msg(msg, {time:2*1000},callback) }; myMsg('msg');`
> 
> 非常感谢，可能我表达的还不够清楚，比如
> 
> ```js
> 		  form.verify({
> 			  username: function(value, item){ //value：表单的值、item：表单的DOM对象
> 			    if(!new RegExp("^[a-zA-Z0-9_\u4e00-\u9fa5\\s·]+$").test(value)){
> 			      return '用户名不能有特殊字符';
> 			    }
> 			    if(/(^\_)|(\__)|(\_+$)/.test(value)){
> 			      return '用户名首尾不能出现下划线\'_\'';
> 			    }
> 			    if(/^\d+\d+\d$/.test(value)){
> 			      return '用户名不能全为数字';
> 			    }
> 			  }
> 			  
> 			  //我们既支持上述函数式的方式，也支持下述数组的形式
> 			  //数组的两个值分别代表：[正则匹配、匹配不符时的提示文字]
> 			  ,pass: [
> 			    /^[\S]{6,12}$/,
> 			    '密码必须6到12位，且不能出现空格'
> 			  ] 
> 			}); 
> ```
> 
> ![img](https://camo.githubusercontent.com/ecd9e240683b40ecdd4ebe722fb7c163df4253f2/68747470733a2f2f7777312e73696e61696d672e636e2f6c617267652f3030367171635838677931673165787a31393531686a333061793038306d78332e6a7067)
> 
> 这个是layui自己的提示，自己二次封装并不能用进去吧 求解

**Comment by chengxuzhang** [comment]
> > 进行二次封装即可
> 
> 不太懂，可以说详细一点吗，

原先的是layer.msg("你好") 这样的话是三秒
你自己写一个函数
var mylayer = function(msg){
    layer.msg(msg,{time:2000});
}
使用方式：mylayer("我擦，居然成功了呢！")

**Comment by qinzhixian** [comment]
你想要的可能是在表单验证那里的tips时间短一点，这个是表单组件封装了的，如果想要修改的话得改源码，后期升级可能会忘掉然后恢复到原来的就不好了，还有一种方式就是自己写校验，可以用验证插件也可以自己手写验证，看怎么抉择了

**Comment by qinzhixian** [comment]
在form.js源码中612行的位置，layui.tips那里，可以加上时间参数

**Comment by galikeoy** [comment]
> > > 进行二次封装即可
> > 
> > 
> > 不太懂，可以说详细一点吗，
> 
> 原先的是layer.msg("你好") 这样的话是三秒
> 你自己写一个函数
> var mylayer = function(msg){
> layer.msg(msg,{time:2000});
> }
> 使用方式：mylayer("我擦，居然成功了呢！")

谢谢你，我已经得到答案了

**Comment by galikeoy** [comment]
> 你想要的可能是在表单验证那里的tips时间短一点，这个是表单组件封装了的，如果想要修改的话得改源码，后期升级可能会忘掉然后恢复到原来的就不好了，还有一种方式就是自己写校验，可以用验证插件也可以自己手写验证，看怎么抉择了

是的，明白了，非常感谢
