### ISSUE TITLE
laydate 

### ISSUE THREAD

**Issue by nonenull** [sentsin/layui#435]

**Comment by nonenull** [comment]
# 假设当表单中有多个项都需要使用laydate 日期选择器 , 且 css class 都指定为  my-date, 渲染后, 只有第一个表单项能正常使用日期选择器, 点击后面的弹出选择器后又闪退.

> 

`    laydate.render({
        type: 'datetime',
        elem: '.my-date'
    });
`

**Comment by qinzhixian** [comment]
现在的laydate组件不支持一个render渲染多个elem，不过社区的岁月小偷有一个帖子是针对这个问题的，可以渲染多个不闪退，你去看一下

**Comment by nonenull** [comment]
> 现在的laydate组件不支持一个render渲染多个elem，不过社区的岁月小偷有一个帖子是针对这个问题的，可以渲染多个不闪退，你去看一下

这个搞定了, 不过还遇到一个奇怪的问题, 关于弹出的日期控件的定位问题

![微信截图_20190326171659](https://user-images.githubusercontent.com/11241809/54985160-441a6480-4feb-11e9-9ecb-c00731fb9c23.png)
时间框挡住了输入框的一半, 然后点击输入框, 也有闪退问题. 
调试了一下, 发现是代码里 Class.prototype.position 里 日期控件 offsetHeight 获取到的高度有问题(比实际高度少30px), 在控件弹出来之后再调试, 高度又是正常的了.

**Comment by qinzhixian** [comment]
设计就是如此，组件和输入框之间会有一个间距的，你可以去官网看一下，每个示例都是这样的

**Comment by nonenull** [comment]
> 设计就是如此，组件和输入框之间会有一个间距的，你可以去官网看一下，每个示例都是这样的

主要是控件它挡住了输入框. 然后如果鼠标点击的位置在输入框和控件的重叠处, 控件就会有闪退的现象.
正常弹出的控件应该是不挡住输入框的

直接在源码 Class.prototype.position 后面加
            if (top + elemHeight < rect.top) {
                top -= 30;
            }
显示就是正常的.
没什么时间排查, 先这样处理了 - -

**Comment by qinzhixian** [comment]
并不是的哦，挡住输入框是因为下方高度不够，然后控件就向上打开了，而且这个输入框是不需要输入的，点击之后是弹出时间选择器，所以挡不挡住都不影响的，当然你可以不用input作为载体，用一个div或者button来当作载体然后打开日期选择器
