### ISSUE TITLE
谷歌浏览器更新到最新版本后，点击文本框，时间控件闪退

### ISSUE THREAD

**Issue by FFeat** [sentsin/layui#441]
![laydateBug](https://user-images.githubusercontent.com/39478005/55137810-e877e480-516c-11e9-8cdb-54f6b032b7e6.gif)

#### 谷歌浏览器更新到最新版本后（版本 73.0.3683.86（正式版本） （64 位）），当弹出的时间控件会覆盖在文本框上面的情况下，这个控件会闪退。
目前只能通过调节弹框高度来解决问题吗？

**Comment by suspring** [comment]
laydate.render({
            elem: '.layui-date' //指定元素
            , trigger: 'click'//
        });
手动设置

**Comment by FFeat** [comment]
> ```
>     laydate.render({
>         elem: '.layui-date' //指定元素
>         , trigger: 'click'//
>     });
> ```
> 
> 手动设置

抱歉现在才关闭。根据回复，问题已经解决了，**感谢！**
