### ISSUE TITLE
 如何在select点击时，加载下拉内容

### ISSUE THREAD

**Issue by diaoyubing** [sentsin/layui#458]
您好，有个问题想请教：
如何在点击select时，加载下拉的内容，像js的click事件。
api中只看到有个form.on('select(chooseName)', function (data) {}）；

因为有一个需求是，下拉值得根据 多个控件值来动态加载的，所以只能在点击时做触发事件。

**Comment by diaoyubing** [comment]
解决

**Comment by animagiq** [comment]
您好，想问下，你是怎么解决，点击加载内容后，进而展示下拉框的问题的？我这边也做了点击动态加载，但是把原本的点击展示下拉框事件给覆盖了，导致只能加载内容，不能展示下拉框。。
