### ISSUE TITLE
table 的 reload 会导致页面越来越卡

### ISSUE THREAD

**Issue by buildazeer** [sentsin/layui#493]
我做应用程序的时候发现，每过一段时间页面就会卡到无法点击，一开始以为是浏览器的问题，后来随着测试用例逐步覆盖，我才发现居然是layui的问题，简直太奇葩了。

到网络上搜了一下，发现已经有人在去年11月提过这个问题，希望贤心快点处理这个问题，解决这个问题并不复杂。

https://fly.layui.com/jie/43925/
https://fly.layui.com/jie/43826/

**Comment by HoneyJoe** [comment]
![image](https://user-images.githubusercontent.com/23476387/59575954-3c50f480-90f0-11e9-9d04-9507f6f8ef60.png)
您好，我在2.2.5版本正常使用reload方法，但是2.5.4版本 必须要用请求接口返回的数据吗？ 如想直接渲染已有的数据 该怎么写？

**Comment by HoneyJoe** [comment]
`tableId.reload({data:data.list,page:{curr:data.currentPage, limit:data.pageSize,count: data.totalRecords}});`
2.2.5是这样写的可以加载数据，2.5.4就不可以了

**Comment by buildazeer** [comment]
不好意思哦，查bug建议还是多写测试用例，我无法直接提供你帮助，也不能替代你写代码

**Comment by HoneyJoe** [comment]
多谢，我重写了二次封装搞定了😊

**Comment by HoneyJoe** [comment]
还是非常感谢，我重写了二次封装搞定了

**Comment by 36304099** [comment]
> 还是非常感谢，我重写了二次封装搞定了

请分享你的封装
