### ISSUE TITLE
npm i layui-src  還是2.5.4?

### ISSUE THREAD

**Issue by eric2100** [sentsin/layui#558]
請問 npm i layui-src  還是 2.5.4 是還沒更新?

**Comment by sentsin** [comment]
您好，确实是忘记了，刚才已经更新。




------------------ 原始邮件 ------------------
发件人: "Tsunghan,Tsai"<notifications@github.com>;
发送时间: 2019年9月17日(星期二) 下午4:33
收件人: "sentsin/layui"<layui@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [sentsin/layui] npm i layui-src  還是2.5.4? (#558)




請問 npm i layui-src  還是 2.5.4 是還沒更新?

**Comment by eric2100** [comment]
謝謝您，速度真快。
