### ISSUE TITLE
强烈要求下一个版本更新时候添加对此功能支持 checkbox 不选中时候表单也包含此类型键值对

### ISSUE THREAD

**Issue by AtlantisDe** [sentsin/layui#577]
## 转送门官方帖子建议链接
-  [强烈要求下一个版本更新时候添加对此功能支持 checkbox 不选中](https://fly.layui.com/jie/58930/)
- [checkbox 开关 就不能默认配置下选中/不选的默认值么?](https://fly.layui.com/jie/57975/)
- [改进下这个组件 开关 这个组件 一次用到一次心痛](https://fly.layui.com/jie/59528/)

![avatar](https://cdn.layui.com/upload/2019_10/3712296_1571729008508_57326.png)

**Comment by hubangmao** [comment]
你这个是特殊场景吧

**Comment by AtlantisDe** [comment]
没有吧? 我角度我思考是正常的  他layui上设计都是能变里面对应的值 这个正是我们需要的 ...关键 off时候就不传出表单对应的值了

胡邦茂 <notifications@github.com> 于2019年10月23日周三 下午2:16写道：

**Comment by AtlantisDe** [comment]
# 无奈之举

```js
var divArr = layui.$("#" + id + " [class='layui-unselect layui-form-switch']");
// console.log(divArr);
layui.$.each(divArr, function(i, n) {
  var input = $(divArr[i]).prev();
  var name = layui.$(input).attr("name");
  console.log(name);
});
```

```c#
// 真是泪崩了哟
// 我知道官方这问题很容易的补出来
// 我一直没想通官方 这么做的用意是出于什么考虑

// 不暴露出来..

// 熬夜下 layui 外挂 先将就着用吧 不知道哪天升级了 脚本又挂了

// 自己随意发挥吧 真是泪崩哇..

// 不知道官方如何考虑这问题的..

```
