### ISSUE TITLE
layer.alert 问题，不确定是Bug还是使用方法问题

### ISSUE THREAD

**Issue by JackieZheng** [sentsin/layui#686]
分别测试哈以下代码：如果不主动关闭，将无限循环！！
`
layer.alert('layer.alert  测试', {
          title: '提示',
          icon: 1,          
          closeBtn: 0
        }, ()=>{ 
           alert('close');           
       }
);
`

`
layer.alert('layer.alert  测试', {
          title: '提示',
          icon: 1,          
          closeBtn: 0
        }, (self)=>{
           layer.close(self); //是否多此一举
           alert('close');           
       }
);
`

**Comment by DidoFitch** [comment]
带回调必须在回调内手动关闭，使用方法问题

**Comment by JackieZheng** [comment]
Nothing to preview
