### ISSUE TITLE
贤大，2.5.6 还没有同步到 npm

### ISSUE THREAD

**Issue by zhengmz** [sentsin/layui#696]
现在 npm i layui-src，只能拿到 2.5.5

**Comment by sentsin** [comment]
现在 npm 移步到了：https://www.npmjs.com/package/layui

**Comment by harkue** [comment]
> 现在 npm 移步到了：https://www.npmjs.com/package/layui

之前用到了老版本， 无法追溯这个版本。

**Comment by zhengmz** [comment]
> 现在 npm 移步到了：https://www.npmjs.com/package/layui

收到，谢谢。
