### ISSUE TITLE
强烈建议优化layui解决跨域的能力！

### ISSUE THREAD

**Issue by leijue222** [sentsin/layui#723]
在table.render需要请求第三方数据，但是遇到了**跨域问题**。
**跨域问题**我看**2018年**就有人提了，可是到**现在还没有被解决**。
前后分离开发的**跨域问题太常见了**，还有请求第三方的时候也有这个问题。自己做后端可以配置，第三方没法配置。
### 强烈建议优化跨域解决方案阿！！

**Comment by leijue222** [comment]
![d75dfdcb34e486c787ea86f0767db69](https://user-images.githubusercontent.com/30276789/86201033-f21ea200-bb90-11ea-9de1-fd8cbe328c73.png)
如图所示是vue在2018年就有的解决方案，只需要在vue.config.js配置域名和端口即可。我很喜欢layui的，但跨域这一点真的很需要加强改善，这个问题是家常便饭，很有必须解决。

**Comment by leijue222** [comment]
@sentsin 希望您能够参考一下我的意见，谢谢！

**Comment by watler-peng** [comment]
> @sentsin 希望您能够参考一下我的意见，谢谢！
百度一下有配置的

**Comment by leijue222** [comment]
> > @sentsin 希望您能够参考一下我的意见，谢谢！
> > 百度一下有配置的

我就是百度了一圈没有找到才提的issue，最终的解决方法只能让后台做几层代理转接。如果你百度到了的话，能否提供一下地址。

**Comment by watler-peng** [comment]
var table = layui.table;
    table.set({
        headers: {
            Authorization: 'Bearer ' + layui.data('layuiAdmin')['Authorization']
        },
        where: { //通过参数传递
            Authorization: 'Bearer ' + layui.data('layuiAdmin')['Authorization']
        }
    });

**Comment by watler-peng** [comment]
> > > @sentsin 希望您能够参考一下我的意见，谢谢！
> > > 百度一下有配置的
> 
> 我就是百度了一圈没有找到才提的issue，最终的解决方法只能让后台做几层代理转接。如果你百度到了的话，能否提供一下地址。

在官方文档里面,你是没逛他们的论坛吧

**Comment by chenxi2008** [comment]
这个table.render里边请求数据不太好呀，为啥不能作成数据我自己请求，组件只做渲染呢，合到一起不好用呀
