### ISSUE TITLE
table组件自定义模板的名称可以改成规范的template吗，templet看着有点奇怪，是有什么原因限制了这个命名吗

### ISSUE THREAD

**Issue by zshnb** [sentsin/layui#796]

**Comment by LSL1618** [comment]
templet和template都是模板的意思，只是template常见得多而已。

**Comment by zshnb** [comment]
> templet和template都是模板的意思，只是template常见得多而已。

但正确的拼写应该就是后者吧，html里的模板标签也是用的template，感觉使用大家公认的名称会更好
