### ISSUE TITLE
脑残框架真够恶心人的 

### ISSUE THREAD

**Issue by coderxuli** [sentsin/layui#826]

**Comment by skyIsland** [comment]
牛皮

**Comment by refcell** [comment]
不想用就别用，何必做喷子

**Comment by littleQing** [comment]
作为UI库可能还不错，但作为项目框架确实很挫。require.js + jquery各种插件的大杂烩

**Comment by z2423065552** [comment]
确实确实

**Comment by qq13011583609** [comment]
你厉害你写一个出来，愿意用就用，不愿意用管好自己的嘴

**Comment by sentsin** [comment]
如果是框架很 low 或者你不喜欢，你完全可以选择不用或者跟身边的人吐槽「layui 是辣鸡」，但是跑到 Issues 这里来喷就完全没必要了。
