### ISSUE TITLE
2.6.5版本日期组件在chrome浏览器中文乱码

### ISSUE THREAD

**Issue by chauncey-lee** [sentsin/layui#864]
日期组件一个星期前还能用，现在在chrome最新版（90）出现中文乱码，包括基于chromium的Edge浏览器。在firefox和IE浏览器正常。我猜测是不兼容chrome90版本

**Comment by sentsin** [comment]
我用 Chrome 90 测试正常：https://www.layui.com/demo/laydate.html

**Comment by yongheng98** [comment]
我也出现了中文乱码的问题。chrome 版本 126.0.6478.127 中文乱码，但是在edge 版本126.0.2592.68里中文可以正常显示，请问是哪里出了问题。

**Comment by yongheng98** [comment]
> 我也出现了中文乱码的问题。chrome 版本 126.0.6478.127 中文乱码，但是在edge 版本126.0.2592.68里中文可以正常显示，请问是哪里出了问题。

已解决，浏览器缓存问题
