### ISSUE TITLE
把这个框架删库吧 真的 因为用你这个框架 都被骂很多次了

### ISSUE THREAD

**Issue by Mrli2016** [sentsin/layui#923]

**Comment by dadaweiwang** [comment]
震惊，这是成年人可以说出口的话吗？
你用框架被骂，怎么不想想是不是你自己的问题？？
选不对框架就要把框架删了是吧？
你被骂老板是不是应该把你炒了？

**Comment by Mrli2016** [comment]
> 震惊，这是成年人可以说出口的话吗？
> 你用框架被骂，怎么不想想是不是你自己的问题？？
> 选不对框架就要把框架删了是吧？
> 你被骂老板是不是应该把你炒了？

有道理 是我错了

**Comment by liuxude** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    这是个傻缺,不用搭理便是,技术选型是自己选的,现在赖框架

    在2021年9月26日 ***@***.***> 写道： 




震惊，这是成年人可以说出口的话吗？

你用框架被骂，怎么不想想是不是你自己的问题？？

选不对框架就要把框架删了是吧？

你被骂老板是不是应该把你炒了？
