### ISSUE TITLE
我已經購買了layuiadmin，我在哪裡可以下載源代碼

### ISSUE THREAD

**Issue by jackpanz** [sentsin/layui#982]
我已經購買了layuiadmin，我在哪裡可以下載源代碼

**Comment by sentsin** [comment]
您好，**layuiAdmin**  ：<a href="https://www.layuion.com/layuiadmin" target="_blank">主页</a> | <a href="https://dev.layuion.com/download/layuiAdmin/" target="_blank">下载</a>（请下载后存档好） | <a href="https://dev.layuion.com/docs/2/" target="_blank">文档</a>
